#ifndef _PLATFORM_H_
#define _PLATFORM_H_

#define PLATFORM_INTERNAL_FLASH_START 0x20000000
#define PLATFORM_INTERNAL_FLASH_SIZE  0x10000

//60kb
#define PLATFORM_PROGRAM_START     PLATFORM_INTERNAL_FLASH_START
#define PLATFORM_PROGRAM_SIZE      0xE000

//8kb
#define PLATFORM_CONFIG_START      (PLATFORM_PROGRAM_START + PLATFORM_PROGRAM_SIZE)
#define PLATFORM_CONFIG_SIZE       0x2000

#endif

